version: '3.8' 
services:
  web:
    container_name: ${PROJECT_NAME}_web 
    build: . 
    working_dir: /code 
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/code
    ports:
      - '8309:8000'
    expose:
      - '8000'
    links:
      - mysql
    networks:
      - bn-network
  mysql:
    container_name: ${PROJECT_NAME}_db
    platform: linux/x86_64 
    image: 'mysql:5.7' 
    volumes:
      - './database/data:/var/lib/mysql'
    ports:
      - '3309:3306'
    networks:
      - bn-network
    environment:
      MYSQL_DATABASE: project 
      MYSQL_ROOT_PASSWORD: password 
networks:
  bn-network:
    driver: bridge
